[zh]
languageName = "简体中文"
languagedirection = "ltr"
title = "人生删除指南"
contentdir = "content/zh"
weight = 30


[en]
languageName = "English"
languagedirection = "ltr"
title = "Life Deletion Guide"
contentdir = "content/en"
weight = 100